name: app-gym
services:
  nginx:
    image: nginx:stable
    container_name: app-gym_nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - 80
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - app-gym_net
      - proxy_net

  php:
    build:
      context: ./
      dockerfile: ./prod.dockerfile
    container_name: app-gym_php
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_CHARSET: ${DB_CHARSET}
    expose:
      - 9000
    volumes:
      - ./app:/var/www/html
      - ./php-config.prod.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-gym_net

  db:
    image: mysql:5.7
    container_name: app-gym_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "healthcheck", "-phealthcheckpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-gym_net

volumes:
  db_data:
    external: true
    name: app-gym_mysql_data

networks:
  app-gym_net:
    driver: bridge
  proxy_net:
    external: true
    name: nginx-proxy_net
