server {
    listen 80;
    server_name gymapp.conin.local;
	
	# Carpeta public
    root /var/www/html;
    index index.php index.html;

    charset utf-8;
    client_max_body_size 20M;

    # Logs
    access_log /var/log/nginx/app-gym.access.log;
    error_log  /var/log/nginx/app-gym.error.log;

    # Enrutamiento
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pasar PHP a php-fpm
    location ~ \.php$ {
        fastcgi_pass    php:9000;
        fastcgi_index   index.php;
        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include         fastcgi_params;
        fastcgi_read_timeout 60;
    }

    # Bloquear acceso a archivos sensibles
    location ~ /\. { deny all; }
    location ~* \.(env|sql|md|gitignore)$ { deny all; }

    # Assets estáticos con caché
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }
}
