; Producción: errores apagados al usuario, logueados internamente
display_errors=Off
log_errors=On
error_reporting=E_ALL

; Opcache
opcache.enable=1
opcache.memory_consumption=128
opcache.max_accelerated_files=10000
opcache.revalidate_freq=60
